project:
  type: website
  output-dir: docs

website:
  title: "Erica J. Lin"
  bread-crumbs: false
  navbar:
    search: true
    left:

     - text: Homework
       menu: 
        - text: SY2025-2026
          file: homework/h2025.qmd

     - text: My Art
       menu: 
        - text: 2024 (5 years)
          file: art/a2024.qmd
        - text: 2025 (6 years)
          file: art/a2025.qmd

     - text: Math and Code
       menu: 
        - text: Math practices
          file: math/m2025.qmd
        - text: Coding playground
          file: math/coding.qmd

     - text: Languages
       menu: 
        - text: 中文
          file: languages/zhongwen.qmd
        - text: English
          file: languages/eng.qmd
                    
     - text: Fun Activities
       menu: 
        - text: Hobbies
          file: fun/hobbies.qmd
        - text: Travels
          file: fun/travels.qmd
        - text: Events
          file: fun/events.qmd          
      

          
     - text: About
       file: about.qmd
       
    tools:
     - icon: envelope
       href: "mailto:erica.jinyi.lin@gmail.com"
       aria-label: email
       

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



